(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const S={api:'',key:'',data:null,round:null,scope:'paper-1',view:'talk',language:'zh',selectedDocuments:{},paperCache:new Map(),questionOpen:new Set(),libraryFilter:'all',filter:'all',messages:[],before:null,reply:null,anchor:null,edit:null,deletion:null,document:null,blob:null,busy:false,draftId:crypto.randomUUID()};
const labels={project:'总方案', 'paper-1':'论文一','paper-2':'论文二','paper-3':'论文三'},variants={source:'原稿 / 材料',zh:'中文稿',en:'英文稿',journal:'投稿润色',plan:'论文方案',deliverable:'工作成果'},kinds={suggestion:'方向建议',question:'待确认问题',decision:'方向结论',update:'修改进展',annotation:'细节批注'},statuses={open:'待讨论',adopted:'已采纳',done:'已落实','needs-owner':'待你确认'};
const el=(t,c,text)=>{const n=document.createElement(t);if(c)n.className=c;if(text!==undefined)n.textContent=text;return n;};
const store={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch{return false;}}};
const date=t=>new Date(t).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
const active=()=>S.data?.rounds.find(r=>r.state==='active');
const chosen=()=>S.data?.rounds.find(r=>r.id===S.round);
const manager=()=>['owner','agent'].includes(S.data?.me.role);
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000);}
function connection(t,error=false){$('#cloud-status').textContent=t;$('#cloud-status').classList.toggle('error',error);}
function openAccess(){S.accessStarted=true;closeWelcome();$('#login-dialog').showModal();requestAnimationFrame(()=>$('#access-key').focus());}
function access(){if(S.data)return true;openAccess();return false;}
function draftKey(){return `cottage:draft:${S.data?.me.role||'guest'}:${S.round}:${S.scope}`;}
function draftSnapshot(){return{body:$('#message-body').value,kind:$('#message-kind').value,reply:S.reply,anchor:S.anchor,id:S.draftId,attempt:S.draftAttempt||null};}
function sameDraft(a,b){return a?.body===b.body&&a.kind===b.kind&&JSON.stringify(a.reply||null)===JSON.stringify(b.reply||null)&&JSON.stringify(a.anchor||null)===JSON.stringify(b.anchor||null);}
function saveDraft(){if(!S.data)return;const ok=store.set(draftKey(),JSON.stringify(draftSnapshot()));$('#draft-status').textContent=ok?'草稿仅在此设备':'草稿未能保存，请勿关闭';}
function restoreDraft(){let d;try{d=JSON.parse(store.get(draftKey()));}catch{}$('#message-body').value=typeof d?.body==='string'?d.body:'';$('#message-kind').value=Object.hasOwn(kinds,d?.kind)?d.kind:'suggestion';S.reply=d?.reply||null;S.anchor=d?.anchor||null;S.draftId=typeof d?.id==='string'?d.id:crypto.randomUUID();S.draftAttempt=typeof d?.attempt==='string'?d.attempt:null;renderReply();}
async function api(path,options={}){
 const headers=new Headers({'X-Cottage-Key':S.key});new Headers(options.headers).forEach((value,name)=>headers.set(name,value));const binary=options.body instanceof ArrayBuffer||ArrayBuffer.isView(options.body)||options.body instanceof Blob;if(options.body&&!(options.body instanceof FormData)&&!headers.has('Content-Type'))headers.set('Content-Type',binary?'application/octet-stream':'application/json');
 const{timeoutMs,raw,...init}=options,response=await fetch(`${S.api}/api${path}`,{...init,headers,signal:AbortSignal.timeout(timeoutMs??(path.endsWith('/complete')?180000:binary||options.body instanceof FormData?120000:30000))});
 if(!response.ok){let detail;try{detail=(await response.json()).error;}catch{}const err=new Error(detail||'云端暂时没有回应，请保留内容再试一次');err.status=response.status;if(response.status===401){connection('访问已过期',true);}throw err;}
 return options.raw?response:response.json();
}
async function login(key,{celebrate=false}={}){
 try{await S.configReady;}catch{const error=new Error('连接信息暂未取回，请刷新页面后重试。');$('#login-error').textContent=error.message;throw error;}
 const session=S.sessionGeneration=(S.sessionGeneration||0)+1;S.key='';S.refreshPending=false;S.refreshFollowActive=false;$('#login-error').textContent='';let accessKey=key.normalize('NFKC').trim();if(/[^\x00-\x7f]/.test(accessKey))accessKey=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(accessKey)))].map(x=>x.toString(16).padStart(2,'0')).join('');if(S.sessionGeneration!==session)return;S.key=accessKey;
 const current=()=>S.sessionGeneration===session&&S.key===accessKey;let data;try{data=await api('/state');if(!current())return;}catch(e){if(!current())return;S.key='';$('#login-error').textContent=e.message;throw e;}
 S.data=data;S.round=active()?.id||null;try{sessionStorage.setItem('cottage:key',S.key);}catch{}$('#access-key').value='';$('#login-dialog').close();renderMeta();restoreDraft();connection('云端已连接');window.HeiExperience?.onAuthenticated(data.me.entryCue,{celebrate});
 try{await loadMessages();}catch(e){if(current()){connection('讨论暂未同步',true);toast('已进入，讨论暂时没有取回。请稍后点「刷新内容」，草稿会保留。');}}
}
async function refresh(quiet=false,{followActive=false}={}){
 if(!S.key)return false;
 S.refreshPending=true;S.refreshQuiet=S.refreshPromise?S.refreshQuiet&&quiet:quiet;S.refreshFollowActive=S.refreshFollowActive||followActive;
 if(S.refreshPromise)return S.refreshPromise;
 S.busy=true;
 S.refreshPromise=(async()=>{
  let synced=false;
  while(S.refreshPending&&S.key){
   const silent=S.refreshQuiet,selectActive=S.refreshFollowActive,key=S.key,session=S.sessionGeneration||0,current=()=>S.key===key&&(S.sessionGeneration||0)===session;S.refreshPending=false;S.refreshQuiet=true;S.refreshFollowActive=false;
   try{
    const data=await api('/state');if(!current())continue;const oldRound=active()?.id;S.data=data;
    if(selectActive){saveDraft();S.round=active()?.id||null;restoreDraft();}else if(!S.round)S.round=active()?.id;
    renderMeta();if(S.view==='talk')await loadMessages();else if(S.view==='library')renderLibrary();if(!current())continue;if($('#history-dialog').open)renderHistory();connection('已同步 '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));if(oldRound&&oldRound!==active()?.id&&S.round===oldRound)toast('新一轮讨论已经开始，可回到当前讨论。');synced=true;
   }catch(e){synced=false;if(!current())continue;connection('同步未完成',true);if(!silent)toast(e.message);}
  }
  return synced;
 })().then(synced=>{S.busy=false;S.refreshPromise=null;return S.refreshPending?refresh(S.refreshQuiet,{followActive:S.refreshFollowActive}):synced;},error=>{S.busy=false;S.refreshPromise=null;throw error;});
 return S.refreshPromise;
}
function renderMeta(){
 const d=S.data,r=chosen()||active();$('#account-button').textContent=d?`${d.me.name} · 退出`:'访问设置';
 $('#export-button').hidden=!d;$('#upload-button').hidden=!d;$('#new-round-button').hidden=!manager()||r?.state!=='active';$('#edit-instructions').hidden=d?.me.role!=='owner';$('#decision-option').hidden=!manager();
 $('#composer-name').textContent=d?.me.role==='owner'?'黑哥 · 说说你的想法':'小小黑，说说你的想法';$('.composer-header .avatar').textContent=d?.me.role==='owner'?'黑':'黑²';$('.composer-header .avatar').className=`avatar ${d?.me.role||'reviewer'}`;
 $('#guest-note').hidden=!!d;$('#composer').hidden=!d||r?.state!=='active';$('#return-current').hidden=!d||r?.state==='active';$('.round-info').hidden=!d;$('#current-todos').hidden=!d;$('#mobile-feedback').hidden=!d||S.view!=='talk';
 if(r){$('#round-number').textContent=`第 ${r.id} 轮`;$('#round-title').textContent=r.title;$('#round-goal').textContent=r.goal;$('#round-state').textContent=r.state==='active'?'正在讨论':'历史轮次';$('#historical-conclusion').hidden=!r.conclusion;$('#historical-conclusion').textContent=r.conclusion;}
 $('#owner-instructions').textContent=d?.settings.owner_instructions?.value||'按照已确认的研究边界推进。';
 if(d?.lastRun){$('#agent-summary').textContent=d.lastRun.summary;$('#agent-last-seen').textContent='最近更新 · '+date(d.lastRun.created_at);}
 renderScopes();renderCarryover();renderPaper();renderTodos();
}
function renderScopes(){
 $('#paper-tabs').replaceChildren(...['paper-1','paper-2','paper-3','project'].map(id=>{const b=el('button',S.scope===id?'active':'',labels[id]);b.setAttribute('aria-pressed',String(S.scope===id));b.onclick=()=>setScope(id);return b;}));
}
function setScope(id){if(!Object.hasOwn(labels,id))return;saveDraft();S.scope=id;restoreDraft();renderScopes();renderPaper();renderFeed();renderCarryover();renderTodos();}
function goCurrentTalk(scope='project'){saveDraft();const next=active()?.id||S.round;if(next!==S.round){S.messages=[];S.before=null;}S.round=next;S.scope=scope;restoreDraft();renderMeta();setView('talk');}
function setView(view){
 if(view==='history'){if(access()){renderHistory();$('#history-dialog').showModal();}return;}
 if(view==='work')view='talk';S.view=view;$('#mobile-feedback').hidden=!S.data||view!=='talk';$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$$('.view').forEach(n=>n.hidden=n.id!==`${view}-view`);$('#paper-tabs').hidden=view!=='talk';$('#quick-guide').hidden=view!=='talk';
 if(view==='library')renderLibrary();if(view==='talk'){renderFeed();renderPaper();if(S.data)loadMessages().catch(e=>toast(e.message));}
}
async function loadMessages(more=false){
 if(!S.round){S.loadSequence=(S.loadSequence||0)+1;S.loadingMessages=false;$('#more-messages').disabled=false;S.messages=[];S.before=null;renderFeed();renderTodos();return;}
 if(S.messageRound!==S.round){S.messageRound=S.round;S.messagePages=1;S.messages=[];S.before=null;}
 const roundAtRequest=S.round,sequence=S.loadSequence=(S.loadSequence||0)+1,key=S.key,session=S.sessionGeneration||0,current=()=>S.round===roundAtRequest&&S.loadSequence===sequence&&S.key===key&&(S.sessionGeneration||0)===session;
 S.loadingMessages=true;$('#more-messages').disabled=true;
 try{
  let cursor=more?S.before:null,loaded=[],pages=0;const requestedPages=more?1:(S.messagePages||1);
  for(let i=0;i<requestedPages;i++){const suffix=cursor?`&before=${cursor.time}&beforeId=${encodeURIComponent(cursor.id)}`:'',result=await api(`/messages?round=${roundAtRequest}${suffix}`);if(!current())return;loaded=[...result.messages,...loaded];cursor=result.before;pages++;if(!cursor)break;}
  const combined=more?[...loaded,...S.messages]:loaded;S.messages=[...new Map(combined.map(m=>[m.id,m])).values()];S.before=cursor;S.messagePages=more?(S.messagePages||1)+pages:pages;renderFeed();
  try{const result=await api(`/questions?round=${roundAtRequest}`);if(!current())return;S.questions=result.questions;S.questionRound=roundAtRequest;S.questionError=false;}
  catch{if(!current())return;S.questionError=true;if(S.questionRound!==roundAtRequest){S.questions=null;S.questionRound=null;}}
  renderTodos();
 }finally{if(S.loadSequence===sequence){S.loadingMessages=false;$('#more-messages').disabled=false;}}
}
function matching(m){return S.scope==='project'||m.paper_id===S.scope;}
function renderFeed(){const feed=$('#discussion-feed');feed.replaceChildren();const filtered=S.messages.filter(m=>matching(m)&&(S.filter==='all'||S.filter==='decisions'&&(m.kind==='decision'||m.status==='done')||S.filter==='pending'&&['open','adopted','needs-owner'].includes(m.status)||S.filter==='questions'&&m.kind==='question'&&m.status!=='done')),matched=new Set(filtered.map(m=>m.id));
 const roots=S.messages.filter(m=>(!m.parent_id||!S.messages.some(p=>p.id===m.parent_id))&&(matched.has(m.id)||S.messages.some(r=>r.parent_id===m.id&&matched.has(r.id))));$('#message-count').textContent=`${filtered.length} 条`;$('#more-messages').hidden=!S.before;
 if(!roots.length){const box=el('div','empty');box.append(el('span','','✧'),el('h3','',S.filter==='questions'?'这篇暂时没有待确认项':'留一个想法吧'),el('p','',S.filter==='questions'?'新的核查问题会集中放在这里。':'一个想法、一个疑问，都可以从这里开始。'));feed.append(box);}
 roots.forEach(m=>{const card=messageCard(m);const replies=S.messages.filter(x=>x.parent_id===m.id);replies.forEach(r=>card.append(messageCard(r,true)));feed.append(card);});
}
function messageCard(m,reply=false){const card=el('article',reply?'reply-card':'message-card'),top=el('div','message-top'),avatar=el('span',`avatar ${m.author_role}`,m.author_role==='reviewer'?'黑':m.author_role==='owner'?'主':'C'),who=el('div');who.append(el('div','message-author',m.author_name),el('div','message-date',`${date(m.created_at)} · ${labels[m.paper_id]||'讨论'}${m.revision>1?' · 已更新':''}`));top.append(avatar,who);if(!reply)top.append(el('span',`badge ${m.status}`,statuses[m.status]||'待讨论'));card.append(top);
 if(m.anchor?.quote)card.append(el('blockquote','message-quote',m.anchor.quote));if(m.document_id){const doc=S.data.documents.find(d=>d.id===m.document_id);const b=el('button','text-button',doc?`↗ ${doc.title}`:'关联稿件已移除');b.disabled=!doc;b.onclick=()=>openDocument(doc);card.append(b);}
 if(m.kind==='question'&&!reply){const detail=el('details','message-question');const lines=m.body.split('\n');detail.append(el('summary','',lines.shift()));detail.append(el('p','message-text',lines.join('\n')));detail.open=S.questionOpen.has(m.id);detail.ontoggle=()=>detail.open?S.questionOpen.add(m.id):S.questionOpen.delete(m.id);card.append(detail);}else card.append(el('p','message-text',m.body));const actions=el('div','message-actions');
 const replyButton=el('button','','回复');replyButton.onclick=()=>startReply(m);actions.append(replyButton);
 if(S.data&&(S.data.me.role===m.author_role||S.data.me.role==='owner')){const edit=el('button','','修改'),del=el('button','','删除');edit.onclick=()=>openEdit('message',m);del.onclick=()=>confirmDelete('message',m);actions.append(edit,del);}
 if(manager()&&!reply){const select=el('select');select.setAttribute('aria-label','处理这条意见');Object.entries(statuses).forEach(([value,label])=>{const o=el('option','',label);o.value=value;o.selected=value===m.status;select.append(o);});select.onchange=async()=>{select.disabled=true;try{await api(`/messages/${m.id}`,{method:'PATCH',body:JSON.stringify({revision:m.revision,status:select.value})});await refresh();}catch(e){toast(e.message);select.value=m.status;}finally{select.disabled=false;}};actions.append(select);}card.append(actions);return card;
}
function renderCarryover(){const pending=(S.data?.carried||[]).filter(m=>matching(m));const box=$('#carryover');box.replaceChildren();box.hidden=!pending.length||chosen()?.state!=='active';if(box.hidden)return;const detail=el('details','carryover-card');detail.append(el('summary','',`前几轮还有 ${pending.length} 项待处理`));pending.forEach(m=>{const row=el('div');row.append(el('p','',`第 ${m.round_id} 轮 · ${labels[m.paper_id]}\n${m.body}`));const b=el('button','text-button','继续反馈 ↗');b.onclick=()=>{const input=$('#message-body'),quote=`接着第 ${m.round_id} 轮的意见聊：\n“${m.body.slice(0,300)}”\n\n`,next=input.value+(input.value?'\n\n':'')+quote;if(next.length>input.maxLength){toast('草稿较长，请先保存当前意见，再接着讨论。');return;}input.value=next;saveDraft();renderReply();input.focus();};row.append(b);if(manager()){const done=el('button','text-button','　标为已落实');done.onclick=async()=>{try{await api(`/messages/${m.id}`,{method:'PATCH',body:JSON.stringify({revision:m.revision,status:'done'})});await refresh();}catch(e){toast(e.message);}};row.append(done);}detail.append(row);});box.append(detail);}
function startReply(m){if(chosen()?.state!=='active'){toast('本轮已归档，请在当前轮次继续反馈。');return;}if(m.paper_id!==S.scope)setScope(m.paper_id);S.reply={id:m.parent_id||m.id,name:m.author_name,text:m.body.split('\n')[0].slice(0,120),paperId:m.paper_id,question:m.kind==='question'?m.body:null};S.anchor=null;renderReply();saveDraft();$('#message-body').focus();$('#composer').scrollIntoView({behavior:'smooth',block:'center'});}
function renderReply(){const c=$('#reply-context');c.replaceChildren();c.hidden=!S.reply&&!S.anchor;if(c.hidden)return;c.append(el('span','',S.anchor?`${S.anchor.paragraph==='whole-document'?'关于':'批注'}「${S.anchor.title}」：${S.anchor.quote}`:`回复 ${S.reply.name}：${S.reply.text}`));const b=el('button','','取消');b.type='button';b.onclick=()=>{S.reply=null;S.anchor=null;renderReply();saveDraft();};c.append(b);if(S.reply?.question){const details=el('details','reply-question');details.open=true;details.append(el('summary','','查看这项需要确认的内容'),el('p','',S.reply.question));c.append(details);}}
async function sendMessage(e){
 e.preventDefault();if(!access())return;const draft=draftSnapshot();if(!draft.body.trim()||S.sending)return;
 const payload={roundId:S.round,paperId:draft.reply?.paperId||S.scope,kind:draft.anchor?'annotation':draft.kind,body:draft.body.trim(),parentId:draft.reply?.id||null,documentId:draft.anchor?.documentId||null,anchor:draft.anchor?{paragraph:draft.anchor.paragraph.trim(),quote:draft.anchor.quote.trim()}:null},signature=JSON.stringify(payload);
 if(S.draftAttempt&&S.draftAttempt!==signature)S.draftId=crypto.randomUUID();S.draftAttempt=signature;saveDraft();const sent={key:draftKey(),id:S.draftId,draft:draftSnapshot(),payload};S.sending=true;const b=$('#send-button');b.disabled=true;
 try{const result=await api('/messages',{method:'POST',body:JSON.stringify({id:sent.id,...payload})}),m=result.message;
  const confirmed=m&&m.id===sent.id&&m.round_id===payload.roundId&&m.paper_id===payload.paperId&&m.kind===payload.kind&&m.body===payload.body&&(m.parent_id||null)===payload.parentId&&(m.document_id||null)===payload.documentId&&(m.anchor?.paragraph||null)===(payload.anchor?.paragraph||null)&&(m.anchor?.quote||null)===(payload.anchor?.quote||null);
  let saved;try{saved=JSON.parse(store.get(sent.key));}catch{}const nextId=crypto.randomUUID();if(saved?.id===sent.id)store.set(sent.key,JSON.stringify({...saved,id:nextId,attempt:null,...(confirmed&&sameDraft(saved,sent.draft)?{body:'',reply:null,anchor:null}:{})}));
  if(draftKey()===sent.key&&S.draftId===sent.id){const unchanged=sameDraft(draftSnapshot(),sent.draft);S.draftId=nextId;S.draftAttempt=null;if(confirmed&&unchanged){$('#message-body').value='';S.reply=null;S.anchor=null;}saveDraft();renderReply();}
  await refresh();toast(confirmed?'收到啦，意见已保存。Codex 会接着处理。':'云端保存的是先前提交的内容，当前修改已保留为草稿，请再次提交。');
 }catch(err){toast(err.message);}finally{S.sending=false;b.disabled=false;}
}
function openEdit(type,record){if(!access())return;S.edit={type,record,updatedAt:type==='instructions'?S.data.settings.owner_instructions?.updatedAt:undefined};$('#edit-title').textContent=type==='instructions'?'Codex · 执行要点':'编辑反馈';$('#edit-label').textContent=type==='instructions'?'对本轮研究的关键意见（优先执行）':'修改意见';$('#edit-body').value=type==='instructions'?S.data.settings.owner_instructions?.value||'':record.body;$('#edit-body').required=type!=='instructions';$('#edit-dialog').showModal();}
function confirmDelete(type,record){S.deletion={type,record};$('#confirm-text').textContent=type==='message'?'删除后，工作台中将不再保留这条意见的正文。已有的独立回复会保留。这个操作无法在页面中撤回。':'删除后，这份稿件将从书架和云端文件存储移除。这个操作无法在页面中撤回。';$('#confirm-dialog').showModal();}
function renderLibrary(){
 const grid=$('#document-grid');grid.replaceChildren();const categories={all:'全部',source:'原始材料',outputs:'稿件与成果'};
 $('#library-filters').replaceChildren(...Object.entries(categories).map(([id,label])=>{const b=el('button',S.libraryFilter===id?'active':'',label);b.onclick=()=>{S.libraryFilter=id;renderLibrary();};return b;}));
 const docs=(S.data?.documents||[]).filter(d=>S.libraryFilter==='all'||(S.libraryFilter==='source'?d.variant==='source':d.variant!=='source'));
 if(!docs.length){grid.append(el('div','empty',S.data?'这里还没有这类文件。':'使用专属分享链接进入后，材料会显示在这里。'));return;}
 docs.forEach(d=>{const c=el('article','document-card');c.append(el('div','doc-symbol',d.content_type==='application/pdf'?'PDF':'文'),el('span','soft-tag',`${labels[d.paper_id]} · ${variants[d.variant]}`),el('h3','',d.title),el('p','',`第 ${d.round_id} 轮 · ${date(d.created_at)}\n${d.size>1048576?(d.size/1048576).toFixed(1)+' MB':(d.size/1024).toFixed(0)+' KB'}`));const b=el('button','button secondary','打开阅读 ↗');b.onclick=()=>openDocument(d);c.append(b);if(S.data.me.role==='owner'){const del=el('button','delete-doc','移除');del.onclick=()=>confirmDelete('document',d);c.append(del);}grid.append(c);});
}
function journalTargets(){try{return JSON.parse(S.data?.settings.journal_targets?.value||'{}');}catch{return {};}}
function journalGuide(){return (S.data?.documents||[]).filter(d=>d.paper_id==='project'&&d.variant==='deliverable'&&/^sci-journal-fit-v[\d.]+\.md$/.test(d.filename)).sort((a,b)=>b.created_at-a.created_at)[0];}
function selectJournalTarget(paper){const select=$('#journal-choice'),target=journalTargets()[paper]||'待确认';select.querySelectorAll('[data-custom-target]').forEach(o=>o.remove());if(![...select.options].some(o=>o.value===target)){const o=el('option','',target);o.value=target;o.dataset.customTarget='true';select.append(o);}select.value=target;}
function openJournal(paper){if(!access())return;S.journalVersion=S.data.settings.journal_targets?.updatedAt;$('#journal-paper').value=paper;selectJournalTarget(paper);$('#journal-guide').hidden=!journalGuide();$('#journal-dialog').showModal();}
function renderTodos(){
 const box=$('#todo-list');box.replaceChildren();if(!S.data)return;
 const scope=S.scope,questionSource=S.questionRound===S.round&&S.questions?S.questions:S.messages,specific=questionSource.filter(m=>m.kind==='question'&&m.status!=='done'&&m.paper_id===scope&&!m.parent_id),common=scope==='project'?[]:questionSource.filter(m=>m.kind==='question'&&m.status!=='done'&&m.paper_id==='project'&&!m.parent_id),questions=[...specific,...common],unanswered=questions.filter(m=>!m.hasReply&&!S.messages.some(r=>r.parent_id===m.id&&['reviewer','owner'].includes(r.author_role)));
 $('#todo-summary').textContent=S.questionError?'待办同步未完成':unanswered.length?`先确认这 ${Math.min(unanswered.length,2)} 项`:questions.length?'已回复，待核查':'先给方向反馈';
 (unanswered.length?unanswered:questions).slice(0,2).forEach(m=>{const b=el('button','todo-item'),title=m.body.split('\n')[0].replace(/^#+\s*/,'');b.append(el('span','',title),el('span','',unanswered.includes(m)?'回答 ↗':'补充 ↗'));b.onclick=()=>startReply(m);box.append(b);});
 if(!questions.length){box.append(el('p','field-hint','是否认可研究方向？哪些内容需要增减？在下面告诉 Codex。'));}
 if(scope!=='project'&&common.length){const shared=el('button','text-button common-todos',`共用材料还有 ${common.length} 项待核对 ↗`);shared.onclick=()=>{setScope('project');$('#current-todos').scrollIntoView({behavior:'smooth',block:'center'});};box.append(shared);}$('#todo-progress').textContent=(S.data.documents||[]).some(d=>d.paper_id===scope&&d.variant==='zh'&&d.content_type==='application/pdf')?'Codex：DEMO 已整理，接着核对反馈与数据。':'Codex：先确认方向，再补充证据。';$('#companion-tip').textContent=S.scope==='paper-3'?'先核对边界，再让想法落地。':'先看整体，有想法就告诉我。';
}
function paperDocuments(){
 const docs=(S.data?.documents||[]).filter(d=>d.paper_id===S.scope&&(!chosen()||chosen().state==='active'||d.round_id<=S.round)&&d.variant!=='source'&&(S.language==='en'?d.variant==='en':d.variant!=='en'));
 const score=d=>d.content_type==='application/pdf'?(d.variant===S.language?6:5):d.variant===S.language?4:d.variant==='plan'?3:2;
 return docs.sort((a,b)=>score(b)-score(a)||b.created_at-a.created_at);
}
async function renderPaper(){
 const sequence=S.paperSequence=(S.paperSequence||0)+1,box=$('#paper-preview'),scope=S.scope,docs=paperDocuments();
 $('#discussion-title').textContent=`${labels[scope]} · 讨论`;$('#paper-number').textContent=scope==='project'?'THE BIG PICTURE':`PAPER ${scope.slice(-1).padStart(2,'0')}`;
 $('#journal-chip').hidden=!S.data||scope==='project';$('#journal-chip').textContent=(journalTargets()[scope]||'拟投待确认')+' ↗';
 $$('#language-picker button').forEach(b=>{b.classList.toggle('active',b.dataset.language===S.language);b.setAttribute('aria-pressed',String(b.dataset.language===S.language));});
 const selected=S.selectedDocuments[scope+S.language],d=docs.find(x=>x.id===selected)||docs[0];S.paperDocument=d||null;
 $('#version-picker').hidden=docs.length<2;$('#paper-version').replaceChildren(...docs.map(x=>{const o=el('option','',x.title);o.value=x.id;o.selected=x.id===d?.id;return o;}));$('#full-reader-button').hidden=!d;
 if(!d){box._pdfController?.destroy();S.renderedPaper=null;$('#paper-title').textContent=S.data?(S.language==='en'?'English abstract · 即将加入':labels[scope]):'论文，从这里开始。';$('#paper-meta').textContent=S.data?'先看整体，再一起打磨。':'黑² · 专属论文空间';const empty=el('div','empty paper-access');empty.append(el('p','',S.data?'本轮稿件正在整理。你可以先阅读中文方案，留下方向建议。':'你的稿件与讨论，已在专属书房等候。'));if(!S.data){const enter=el('button','button secondary','用口令打开论文 ↗');enter.onclick=openAccess;empty.append(enter);}box.replaceChildren(empty);return;}
 const demoLabel=d.title.match(/DEMO\s+v[\d.]+/i)?.[0];$('#paper-title').textContent=d.title.replace(/\s*DEMO\s+v[\d.]+/i,'').trim();$('#paper-meta').textContent=`${demoLabel||variants[d.variant]} · ${date(d.created_at)}${/demo|示意/i.test(d.title)?' · 仅供讨论，非投稿稿':''}`;
 if(S.renderedPaper===d.id)return;S.renderedPaper=null;box._pdfController?.destroy();box.replaceChildren(el('div','empty','正在取回稿件…'));
 const current=()=>sequence===S.paperSequence&&S.scope===scope&&S.paperDocument?.id===d.id;
 try{
  let cached=S.paperCache.get(d.id);
  if(!cached){if(d.content_type!=='application/pdf'&&!d.content_type.startsWith('text/')){box.replaceChildren(el('div','empty','点击「展开阅读」下载原始文件。'));return;}const response=await api(`/documents/${d.id}`,{raw:true,timeoutMs:180000}),blob=await response.blob();if(blob.size!==d.size)throw new Error('稿件传输不完整，请刷新后再试。');cached=d.content_type==='application/pdf'?{blob}:{text:await blob.text()};S.paperCache.set(d.id,cached);}
  if(!current())return;if(S.paperBlob)URL.revokeObjectURL(S.paperBlob);S.paperBlob=null;box.replaceChildren();box.scrollTop=0;
  if(cached.blob){const {mountPdf}=await import('./pdf-reader.js?v=20260924-salon02');if(!current())return;await mountPdf(box,cached.blob,d.title);if(!current())return;const fallback=el('button','text-button pdf-fallback','下载 PDF ↗');fallback.onclick=()=>downloadBlob(cached.blob,d.filename);box.append(fallback);}
  else cached.text.split(/\n\s*\n/).filter(Boolean).forEach(text=>box.append(markdownBlock(text)));
  S.renderedPaper=d.id;
 }catch(e){if(current()){const retry=el('button','button secondary','重新取回稿件');retry.onclick=()=>renderPaper();box.replaceChildren(el('p','field-hint',e.message),retry);}}
}
function renderHistory(){const list=$('#round-timeline');list.replaceChildren();if(!S.data?.rounds.length){list.append(el('div','empty','进入工作台后，我们的讨论记录会出现在这里。'));return;}S.data.rounds.forEach(r=>{const card=el('article','timeline-card');card.append(el('span','soft-tag',`第 ${String(r.id).padStart(2,'0')} 轮 · ${r.state==='active'?'正在进行':'已整理'}`),el('h3','',r.title),el('p','',r.conclusion||r.goal));const b=el('button','text-button',r.state==='active'?'回到这轮讨论 ↗':'翻看这轮讨论 ↗');b.onclick=async()=>{saveDraft();S.round=r.id;S.messages=[];S.before=null;restoreDraft();$('#history-dialog').close();renderMeta();setView('talk');try{await loadMessages();}catch(e){toast(e.message);}};card.append(b);list.append(card);});}
function openUpload(paperId=S.scope){if(!access())return;$('#document-paper').value=paperId;$('#upload-dialog').showModal();}
async function uploadHash(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');}
async function uploadFile(file,metadata,progress){
 const token=S.key,identity=await uploadHash(new TextEncoder().encode(token)),request=async(path,options={})=>{if(S.key!==token)throw new Error('进入身份已变化，请重新进入后继续上传。');return api(path,{...options,headers:{...options.headers,'X-Cottage-Key':token}});};
 if(file.size<=3*1024*1024){const form=new FormData();for(const[key,value]of Object.entries({id:crypto.randomUUID(),...metadata}))form.set(key,String(value));form.set('file',file);return request('/documents',{method:'POST',body:form});}
 progress('正在校验原始文件…');const sha256=await uploadHash(await file.arrayBuffer()),signature=await uploadHash(new TextEncoder().encode(JSON.stringify([S.api,identity,sha256,metadata.paperId,metadata.variant,metadata.roundId,metadata.title,file.name,file.size]))),storageKey=`cottage:upload:${signature}`;
 let record;try{record=JSON.parse(store.get(storageKey));}catch{}const persist=()=>{if(!store.set(storageKey,JSON.stringify(record)))throw new Error('无法保存续传记录，请允许浏览器保存本地数据后重试。');};
 if(record?.id){let previous;try{previous=await request(`/uploads/${encodeURIComponent(record.id)}`);}catch(err){if(err.status!==404)throw err;}if(previous?.state==='complete')return{id:record.id,duplicate:true};if(previous?.state==='aborted')record=null;else if(previous&&Date.now()-(record.createdAt||0)>6*24*60*60*1000){await request(`/uploads/${encodeURIComponent(record.id)}`,{method:'DELETE'});record=null;}}
 if(!record?.id){record={id:crypto.randomUUID(),tokenFingerprint:identity,sha256,metadata:{...metadata,filename:file.name,size:file.size,sha256},createdAt:Date.now(),parts:[]};persist();}
 let status=await request('/uploads',{method:'POST',body:JSON.stringify({id:record.id,...record.metadata})});if(status.state==='complete')return{id:record.id,duplicate:true};if(status.state!=='uploading'&&status.state!=='completing')throw new Error('上传任务已结束，请重新选择文件。');if(![4*1024*1024,8*1024*1024].includes(status.chunkSize))throw new Error('云端分片配置不匹配，请稍后重试。');
 const completed=new Map(status.parts.map(part=>[part.partNumber,part])),count=Math.ceil(file.size/status.chunkSize),retry=async(path,options)=>{for(let attempt=0;attempt<3;attempt++){try{return await request(path,options);}catch(err){if(attempt===2||err.status&&err.status<500&&err.status!==429)throw err;progress('网络暂时中断，正在重试…');await new Promise(resolve=>setTimeout(resolve,1000*(attempt+1)));}}};
 for(let number=1;number<=count;number++){const offset=(number-1)*status.chunkSize,bytes=await file.slice(offset,Math.min(offset+status.chunkSize,file.size)).arrayBuffer(),hash=await uploadHash(bytes),saved=completed.get(number);if(saved&&(saved.sha256!==hash||saved.size!==bytes.byteLength))throw new Error('文件分片与续传记录不一致，请保留原文件。');
  if(!saved){progress(`正在上传 ${number} / ${count} 分片…`);const receipt=await retry(`/uploads/${record.id}/parts/${number}`,{method:'PUT',body:bytes,headers:{'Content-Type':'application/octet-stream','X-Upload-SHA256':hash},timeoutMs:120000});completed.set(number,receipt);record.parts=[...completed.values()];persist();}progress(`已上传 ${Math.round(Math.min(offset+status.chunkSize,file.size)/file.size*100)}%（${number}/${count}）`);
 }
 progress('正在确认完整文件…');const result=await retry(`/uploads/${record.id}/complete`,{method:'POST',timeoutMs:120000});record.completedAt=Date.now();record.result=result;persist();return result;
}
function richText(tag,text){
 const node=el(tag),tokens=/(\*\*[^*]+\*\*|\[[^\]\n]+\]\(https:\/\/[^\s()<>"']+\)|https:\/\/[^\s；。，（）<>"'\[\]()]+)/g;
 text.split(tokens).filter(Boolean).forEach(part=>{const link=part.match(/^\[([^\]\n]+)\]\((https:\/\/[^\s()<>"']+)\)$/);if(part.startsWith('**')&&part.endsWith('**'))node.append(el('strong','',part.slice(2,-2)));else if(link||part.startsWith('https://')){const a=el('a','',link?link[1]:part);a.href=link?link[2]:part;a.target='_blank';a.rel='noopener noreferrer';node.append(a);}else node.append(document.createTextNode(part));});return node;
}
function markdownBlock(text){const heading=text.match(/^(#{1,3})\s+(.+)$/);if(heading)return richText('h'+Math.min(heading[1].length+1,4),heading[2]);const lines=text.split('\n');if(lines.length>2&&lines[0].startsWith('|')&&/^\|[\s:|\-]+\|$/.test(lines[1])){const wrap=el('div','reader-table'),table=el('table');lines.filter((_,i)=>i!==1).forEach((line,i)=>{const row=el('tr');line.replace(/^\||\|$/g,'').split('|').forEach(cell=>row.append(richText(i?'td':'th',cell.trim())));table.append(row);});wrap.append(table);return wrap;}if(lines.every(line=>/^(?:- |\d+\. )/.test(line))){const list=el(/^\d/.test(text)?'ol':'ul');lines.forEach(line=>list.append(richText('li',line.replace(/^(?:- |\d+\. )/,''))));return list;}return richText('p',text);}
function discussDocument(d,paragraph='whole-document',quote='关于这份文件的反馈'){if(!d||!active()){toast('请先建立当前讨论轮次。');return;}saveDraft();const changedRound=S.round!==active().id;S.round=active().id;S.scope=d.paper_id;if(changedRound){S.messages=[];S.before=null;}restoreDraft();S.reply=null;S.anchor={documentId:d.id,title:d.title,paragraph,quote};$('#reader-dialog').close();$('#history-dialog').close();setView('talk');renderMeta();renderReply();saveDraft();$('#message-body').focus();loadMessages().catch(e=>toast(e.message));}
async function openDocument(d){if(!access())return;const sequence=S.documentSequence=(S.documentSequence||0)+1,isCurrent=()=>S.documentSequence===sequence&&S.document===d&&$('#reader-dialog').open;if(S.blob)URL.revokeObjectURL(S.blob);S.blob=null;$('#document-download').disabled=true;S.document=d;$('#document-download').textContent='下载文件';$('#reader-title').textContent=d.title;$('#reader-content')._pdfController?.destroy();$('#reader-content').replaceChildren(el('p','','正在从云端取回稿件…'));$('#annotation-switch').checked=false;$('#reader-content').classList.remove('annotating');$('.annotation-switch').hidden=!d.content_type.startsWith('text/');$('#reader-dialog').showModal();if(d.content_type!=='application/pdf'&&!d.content_type.startsWith('text/')){$('#reader-content').replaceChildren(el('div','empty','原始文件已保留。点击下载查阅，或在讨论区补充意见。'));$('#document-download').disabled=false;return;}try{const response=await api(`/documents/${d.id}`,{raw:true,timeoutMs:180000});const blob=await response.blob();if(blob.size!==d.size)throw new Error('文件传输不完整，请重新打开或下载。');if(!isCurrent())return;$('#document-download').disabled=false;if(S.blob)URL.revokeObjectURL(S.blob);S.blob=URL.createObjectURL(blob);const reader=$('#reader-content');reader.replaceChildren();
 if(d.content_type==='application/pdf'){const {mountPdf}=await import('./pdf-reader.js?v=20260924-salon02');if(!isCurrent())return;await mountPdf(reader,blob,d.title,{expanded:true});}
 else if(d.content_type.startsWith('text/')){const text=await blob.text();if(!isCurrent())return;if(text.length>1500000){reader.append(el('p','','文字稿较大，请下载阅读。'));return;}text.split(/\n\s*\n/).filter(Boolean).forEach((text,i)=>{const p=el('div','reader-paragraph');p.append(markdownBlock(text));const b=el('button','','＋');b.title='批注这一段';b.setAttribute('aria-label',`批注第 ${i+1} 段`);b.onclick=()=>discussDocument(d,`p-${i+1}`,text.slice(0,800));p.append(b);reader.append(p);});}
 else reader.append(el('div','empty','这份 Word 稿件可以下载到本地阅读。助手也可以据此生成便于批注的文字稿。'));
 }catch(e){if(isCurrent())$('#reader-content').replaceChildren(el('p','',e.message));}}
function downloadBlob(blob,name){const a=el('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function registerTools(){if(!document.modelContext?.registerTool)return;const tools=[{name:'read_cottage_workspace',description:'读取已进入的论文工作台当前轮次、讨论和稿件列表；不会返回口令。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>S.data?{role:S.data.me.role,view:S.view,scope:S.scope,round:chosen(),instructions:S.data.settings.owner_instructions?.value||'',messages:S.messages,documents:S.data.documents}:{locked:true}},{name:'navigate_cottage_view',description:'切换工作台的方向讨论、稿件书架或轮次历史，不提交任何内容。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['work','talk','library','history']},scope:{type:'string',enum:Object.keys(labels)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!['work','talk','library','history'].includes(input.view)||input.scope&&!Object.keys(labels).includes(input.scope))throw new Error('无效的工作台页面');if(input.scope)setScope(input.scope);setView(input.view);return{view:S.view,scope:S.scope};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
function closeWelcome(){store.set('hei2:welcomed','yes');$('#welcome-dialog').close();}
async function init(){
 registerTools();renderMeta();setView('talk');S.configReady=fetch('cloud-config.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('连接信息暂未取回');return r.json();}).then(config=>{S.api=['localhost','127.0.0.1'].includes(location.hostname)?'':config.api;});await S.configReady;
 const hash=new URLSearchParams(location.hash.slice(1));let key=hash.get('invite');if(key)history.replaceState(null,'',location.pathname+location.search);else try{key=sessionStorage.getItem('cottage:key');}catch{}
 if(key){try{await login(key);}catch{renderMeta();connection('请检查分享链接',true);}}else connection('专属论文空间');
 if(store.get('hei2:welcomed')!=='yes'&&!S.accessStarted&&!$('dialog[open]'))$('#welcome-dialog').showModal();
}
$$('.nav').forEach(n=>n.onclick=()=>setView(n.dataset.view));$$('.feed-filters button').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;$$('.feed-filters button').forEach(n=>n.classList.toggle('active',n===b));renderFeed();});
$('#access-key').addEventListener('compositionstart',()=>S.accessComposing=true);$('#access-key').addEventListener('compositionend',()=>S.accessComposing=false);$('#access-key').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.isComposing||S.accessComposing||e.keyCode===229))e.preventDefault();});
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',e.target);if(S.accessComposing||b.disabled)return;b.disabled=true;try{await login($('#access-key').value,{celebrate:true});}catch{}finally{b.disabled=false;}};
$('#welcome-dialog').addEventListener('cancel',()=>store.set('hei2:welcomed','yes'));$('#welcome-dialog').onclick=e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeWelcome();}};
$('#account-button').onclick=()=>{if(!S.data){openAccess();return;}saveDraft();S.sessionGeneration=(S.sessionGeneration||0)+1;S.key='';S.data=null;S.refreshPending=false;S.refreshFollowActive=false;try{sessionStorage.removeItem('cottage:key');}catch{}location.reload();};
$('#refresh-button').onclick=()=>{if(access())refresh();};$('#message-body').oninput=saveDraft;$('#message-kind').onchange=saveDraft;$('#composer').onsubmit=sendMessage;
$('#edit-instructions').onclick=()=>{$('#instructions-dialog').close();openEdit('instructions');};$('#edit-form').onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',e.target);b.disabled=true;try{if(S.edit.type==='instructions')await api('/instructions',{method:'PUT',body:JSON.stringify({value:$('#edit-body').value,updatedAt:S.edit.updatedAt})});else await api(`/messages/${S.edit.record.id}`,{method:'PATCH',body:JSON.stringify({body:$('#edit-body').value,revision:S.edit.record.revision})});$('#edit-dialog').close();await refresh();toast('修改已经保存到云端。');}catch(err){toast(err.message);}finally{b.disabled=false;}};
$('#new-round-button').onclick=()=>{S.roundEdit={previousId:active()?.id};$('#round-dialog').showModal();};$('#round-form').onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',e.target);b.disabled=true;try{await api('/rounds',{method:'POST',body:JSON.stringify({previousId:S.roundEdit?.previousId,conclusion:$('#round-conclusion-input').value,title:$('#next-round-title').value,goal:$('#next-round-goal').value})});saveDraft();$('#round-dialog').close();e.target.reset();const synced=await refresh(false,{followActive:true});toast(synced?'新轮次已建立，旧轮次已归档。':'新轮次已建立，同步暂未完成。请刷新后回到当前讨论。');}catch(err){toast(err.message);}finally{b.disabled=false;}};
$('#upload-button').onclick=()=>openUpload();$('#upload-form').onsubmit=async e=>{e.preventDefault();if(S.uploading||!access())return;const file=$('#document-file').files[0];if(!file||!file.size||file.size>300*1024*1024){toast('请选择 300 MB 以内的非空文件。');return;}if(!active()){toast('请先建立第一轮讨论。');return;}const metadata={title:$('#document-title').value.trim(),paperId:$('#document-paper').value,variant:$('#document-variant').value,roundId:active().id},b=$('[type=submit]',e.target),previous=b.textContent,controls=[...e.target.elements].filter(control=>!control.classList.contains('close-dialog')).map(control=>[control,control.disabled]);S.uploading=true;controls.forEach(([control])=>control.disabled=true);b.textContent='正在保存稿件…';try{await uploadFile(file,metadata,text=>b.textContent=text);$('#upload-dialog').close();e.target.reset();await refresh();setView('library');toast('文件已保存到云端。');}catch(err){toast(err.message+(file.size>3*1024*1024?' 已完成的分片会保留，重新选择同一文件和相同信息可继续上传。':''));}finally{S.uploading=false;controls.forEach(([control,disabled])=>control.disabled=disabled);b.textContent=previous;}};
$('#confirm-delete').onclick=async()=>{const b=$('#confirm-delete');b.disabled=true;try{const d=S.deletion;await api(`/${d.type==='message'?'messages':'documents'}/${d.record.id}`,{method:'DELETE',body:JSON.stringify({revision:d.record.revision})});$('#confirm-dialog').close();await refresh();toast('内容已从工作台移除。');}catch(e){toast(e.message);}finally{b.disabled=false;}};
$('#document-download').onclick=async()=>{const d=S.document;if(!d)return;if(S.blob){const a=el('a');a.href=S.blob;a.download=d.filename;a.click();return;}const b=$('#document-download'),sequence=S.documentSequence;b.disabled=true;const prior=b.textContent;b.textContent='正在下载…';try{const response=await api(`/documents/${d.id}`,{raw:true,timeoutMs:300000});const blob=await response.blob();if(blob.size!==d.size)throw new Error('文件传输不完整，请重试下载。');downloadBlob(blob,d.filename);}catch(e){toast(e.message);}finally{if(S.documentSequence===sequence){b.disabled=false;b.textContent=prior;}}};$('#document-discuss').onclick=()=>discussDocument(S.document);$('#reader-dialog').addEventListener('close',()=>{if($('#reader-dialog').open)return;S.documentSequence=(S.documentSequence||0)+1;$('#reader-content')._pdfController?.destroy();S.document=null;if(S.blob)URL.revokeObjectURL(S.blob);S.blob=null;});
$('#journal-guide').onclick=()=>{const doc=journalGuide();if(!doc){toast('筛选建议已更新，请刷新后查看。');return;}$('#journal-dialog').close();openDocument(doc);};
$('#journal-paper').onchange=()=>selectJournalTarget($('#journal-paper').value);$('#journal-form').onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',e.target);b.disabled=true;try{const targets={...journalTargets(),[$('#journal-paper').value]:$('#journal-choice').value};await api('/journal-targets',{method:'PUT',body:JSON.stringify({targets,updatedAt:S.journalVersion})});$('#journal-dialog').close();await refresh();toast('拟投方向已保存。');}catch(err){toast(err.message);}finally{b.disabled=false;}};
$('#more-messages').onclick=()=>loadMessages(true).catch(e=>toast(e.message));$('#export-button').onclick=async()=>{try{const data=await api('/export');downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`论文工作台记录-${new Date().toISOString().slice(0,10)}.json`);}catch(e){toast(e.message);}};
$('#help-button').onclick=()=>$('#help-dialog').showModal();$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#mobile-feedback').onclick=()=>{goCurrentTalk(S.scope);$('#composer').scrollIntoView({behavior:'smooth',block:'center'});$('#message-body').focus({preventScroll:true});};$('#history-button').onclick=()=>setView('history');$('#instructions-button').onclick=()=>{if(access())$('#instructions-dialog').showModal();};$('#welcome-button').onclick=()=>$('#welcome-dialog').showModal();$('#close-welcome').onclick=closeWelcome;$('#start-reading').onclick=closeWelcome;$('#open-access').onclick=openAccess;$('#library-upload').onclick=()=>openUpload('project');$('#return-current').onclick=()=>goCurrentTalk(S.scope);
$('#paper-version').onchange=()=>{S.selectedDocuments[S.scope+S.language]=$('#paper-version').value;renderPaper();};$('#full-reader-button').onclick=()=>{if(S.paperDocument)openDocument(S.paperDocument);};$('#journal-chip').onclick=()=>openJournal(S.scope);$('#annotation-switch').onchange=e=>$('#reader-content').classList.toggle('annotating',e.target.checked);
$$('#language-picker button').forEach(b=>b.onclick=()=>{S.language=b.dataset.language;renderPaper();});$$('#more-menu button').forEach(b=>b.addEventListener('click',()=>$('#more-menu').open=false));document.addEventListener('click',e=>{if(!$('#more-menu').contains(e.target))$('#more-menu').open=false;});
window.addEventListener('beforeunload',saveDraft);setInterval(()=>{if(!document.hidden&&S.data&&!S.loadingMessages&&!$$('dialog[open]').length)refresh(true);},60000);
init().catch(()=>{connection('连接配置读取失败',true);toast('工作台暂时未能连接，请刷新后重试。');});
})();
